### Working with Numpy

In [2]:
import sys
import numpy as np

In [3]:
array_1d = np.array ([4,5,6])
type(array_1d)

numpy.ndarray

In [4]:
array_1d.ndim

1

In [5]:
matriz = np.array (
   [ [1,2,3],
    [4,5,6]]
)

matriz.ndim

2

In [7]:
np.eye(3)
    

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
lista_2d = [[2,3], [4,5,6]]
array_2d = np.array(
    [[2,3],
    [4,5,6]])

print(sys.getsizeof(lista_2d))
print(sys.getsizeof(array_2d))

80
112


In [13]:
%%timeit
sum(range(100000000))

5.21 s ± 227 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%%timeit
np.sum(range(1000))

137 µs ± 9.94 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [26]:
matriz3x4 = np.array (
    [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ]
)

matriz3x4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
matriz3x4[0]

array([1, 2, 3, 4])

In [33]:
matriz[:,0]

array([1, 4])

In [34]:
matriz[1,1]

5

In [35]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[10,15],[20,30]])
#m1*m2
m1 @ m2

array([[ 50,  75],
       [110, 165]])

### Exercise with Numpy

In [1]:
# Import numpy and make an array 
import numpy as np

In [2]:
array = np.array([
 [1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]
])

In [24]:
#Check the form of the array
array.shape

(5, 3)

In [6]:
#Select the second column of the array
array[:,1]

array([ 6,  7,  8,  9, 10])

In [19]:
#Create a vector with values 15-55
array2 = np.arange(15,55)

In [20]:
#assign 23 in five postion of the array2
array2[4]=23

In [21]:
#inverse vector
array2 = array2[::-1]
array2

array([54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38,
       37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 23, 18, 17, 16, 15])

In [25]:
matriz_diag = np.diag(array2[1::2][:5])

In [26]:
matriz_diag

array([[53,  0,  0,  0,  0],
       [ 0, 51,  0,  0,  0],
       [ 0,  0, 49,  0,  0],
       [ 0,  0,  0, 47,  0],
       [ 0,  0,  0,  0, 45]])

In [27]:
matriz_diag.ndim

2

In [28]:
mRandom = np.random.random((5,3))

In [30]:
mRandom.shape

(5, 3)

In [31]:
matriz_diag.shape

(5, 5)

In [32]:
mRandom.T.shape

(3, 5)

In [35]:
matriz_diag @ mRandom

array([[20.23811223, 24.5519025 , 19.87906149],
       [20.72556627,  2.66986482, 31.00048589],
       [ 3.31218348,  3.64545575, 46.39658467],
       [ 5.79362306, 22.38826684,  7.88363749],
       [27.03137003, 36.80002924,  6.07564303]])